name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('./yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable

  Build:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: restore-build-cache
        uses: actions/cache@v2
        with:
          path: build
          key: build-${{ github.sha }}
      - if: steps.restore-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('./yarn.lock') }}
      - if: steps.restore-build-cache.outputs.cache-hit != 'true'
        env:
          REACT_APP_AUTH_CLIENT_ID: ${{ secrets.REACT_APP_AUTH_CLIENT_ID }}
          REACT_APP_AUTH_CLIENT_SECRET: ${{ secrets.REACT_APP_AUTH_CLIENT_SECRET }}
          REACT_APP_AUTH_ENDPOINT: ${{ secrets.REACT_APP_AUTH_ENDPOINT }}
          REACT_APP_AUTH_TOKEN_ENDPOINT: ${{ secrets.REACT_APP_AUTH_TOKEN_ENDPOINT }}
          REACT_APP_API_DOMAIN: ${{ secrets.REACT_APP_API_DOMAIN }}
        run: yarn build

  ESLint:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn check:eslint

  Prettier:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn check:prettier

  Deploy:
    if: github.event_name == 'push'
    needs: [Build, ESLint, Prettier]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: build
          key: build-${{ github.sha }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KITTY_SAYS_MEOW }}'
          channelId: live
          projectId: kitty-says-meow
